name: Build and Push Alpine Nginx

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build Docker Image
      run: docker build -t sungminwoo0612/alpine-nginx:latest -f docker/alpine-nginx/Dockerfile.alpine-nginx .
    
    - name: Push Docker Image
      run: docker push sungminwoo0612/alpine-nginx:latest
